version: "3"

services:
  hashapi:
    image: 'spai22/hashapi'
    command:  uvicorn main:app --workers 1 --host 0.0.0.0 --port 8090
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - hash_network
    environment:
      HASHCMD: hash
      HASHFILECMD: validate

networks:
  hash_network:
    driver: bridge
